matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd webapp

    - language: csharp
      sudo: required
      services:
        - docker
      mono: none
      dotnet: 2.0.0
      env:
        - COMMIT=${TRAVIS_COMMIT::8}
        # DOCKER_EMAIL
        - secure: "ir44qiSE9OJ2UPcmQd8uTiCVawLV1mrRkWlxmyR771UGKFk9d+OiFdkrjAzcCzrI2FSjfRtCc/3xkLRo4YsZ1kNccRm7epktOr2Dyp/b9lI7Q5qGqZXXWFJ11d1pobSKRDm5kWYc5F0nycPOaWQmqMV/YEftOcAlolOr7QNtetoFn79dzWgnP10O9CXDVv9vd5m/19EGgStWLnr+oZYWR9CGdfHWGlRIJGBRw8SwMYxVnFv0s2kp5LceXzQWRcxpKpgQGSLu8r9aKQHen2aGGhLf+o2CVwBsQ4eYkhnTeBg1jbNVWP/6qOvI+lsU6F4y4nzZcW3ihiFJj71djr0/+0/TeUnI3SVMI09iJnS7MLkKPysKHrmrhZ7GNEwy/J6+O/cM5sV4thzdLmAgX2Y3VBPEPfcx6ZrXyJz25U+gloAtNpnvd0R0wtErDL5C6FmpgyDJgTfhjOnKH4x5zZk7k2EPGdFMxtQ28HhtHbqmKrxUnsieoD58T13TX1zChQI10NjvBnsJd6T5bs7cXmXyxjy2QETYc+HQeL5bCWZCJwkTNOb2/6CC60NnoYCDwX2uVJrKqzN5UVxYwMrhGZJHzxV206kmiCxnuu0Od00/LD1I6mVD9MPmoJ6ofFixJw+DmjRr/ihvP04tg6LSFhnFhhODZ8SSvxgrknPIxUY0EOw="
        # DOCKER_USER
        - secure: "Tmm/PeeMNFG0+rHwHt8K5kCdiUHlk9OIxzgD40rbjdS8YRR/OP0qUPy81b7wTca1DJFUxfV/t29evmg2X0p8fzxrDfKHRz16nKQwHRmcnsIhBLlutCTlfYXHRVP9EZLz4Bb2IAaAVEKBfnkvU9vkO4o9lw6m9ASKTJdV28cs2sb6pQ4aRJZbQQSOd+FUtxPfYtlU9MbH20lEpiZtbCh/mZitj1nNX/pXoKxlL5Fa1DMmr8lK+sXCea5VC/zJhxm276lMWfJfTajUVEl+5KR1LSkClPvuBbNZHsRzwz5fsMGi01RoW+/iGz0HP0alouZ8qJ1IQEpcHNLreGjJXdKQy+18GOAgP39tzlFzmjC2mSBZYRlWWpGsxZprX2CyGBNDGRzAHs3U2RoD+akyOTMjIMaFql6Nl6owNWkGpTkQ0zuM+YXypbt0mZfjwqwb5tJDl2pEPL9aBBH1bPgVtETVZ7wipr8MXVMn8os+gKBHcCD9uLg6OFpSKiFBDHThxYwpTuvvO7zxj8+ufX0V3pmPqzm7WL2T4f2oB8lQ45Qf9kl9D4F75Hgw+Ekr9PW2acytqql5LP+fwklZ5Z/G+ZKOv9E2OC0aNE0vhWhSlFZk0HoF2sX5vyj+fPI86/fTz3IMGz0cdMTN2znLL5n+P2elFxcnrokaf25qdbbjCHxlA+E="
        # DOCKER_PWD
        - secure: "OvFhVdOT2OfLPQ6k5k5wRbRlWSz9jzQk50hXFlCJa8k8W4/jxpddM60j95SobqqkbjIYs004FDApl0A8g2VvAuYPft+LabSeXnZUCpOrxLWB+6iTH5s+suMBrGiwgp/2HQniPYggZlDHTttNrWnm4PFaFFr7O+XQS5BO2u4k3raOZt9pa5VvVNiVmE50Qu0KYrYBNqB51qR+/eGd+FvF/ejJRgJeTdAV6rZpz/cpXVmSPjUsnzNRqaLAu43pJnN05FzkEmxB2OvMnOCVrsxzjXo6Ce0ospE6V/CIB9RxDEvAWyjLaGWbLQj6mblO1Ahi4omYwSD6yxDnqk1YUVFx/8kP2BdL0M/TOdOko+UngMa62B20cf3DFO2NA5apJNf1RPIynuN2Mw/c5WMhPyAx8R/+8Sv65fjWCzGVRGZWy6cXWN85exbnPgwRU7hQO6GNxXXRCZeEYcv3XKjteU5FNCNQzZLSAlmMXta5H1ek4eulX2E2ds9QwjmH8ue3ag0mwyfJ4AmM7y5hbLUbWo7cWyyKpNx0G14yRYMolvLVbC6sXzm1DgyAhAa3iT/kkfctkaMvLc4+yMzPtDPTQWo8D25s+wDikOnvgL6r6RH09FLyUU5TwoNWwWDQNhO4MrcBAtPbJ3+glctnm8c0XCe5S3MnuEkkE1pdF/26gLmV1Yw="
      before_install:
        - cd data-api
      script:
        - dotnet restore
        - dotnet build
        - dotnet publish -o pack
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PWD
        - docker build -t $DOCKER_USER/commute-data-api:2.0.0.$COMMIT .
        - docker push $DOCKER_USER/commute-data-api:2.0.0.$COMMIT